name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Cambia la rama si es necesario

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Especifica la versión de Node.js que deseas usar

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build  # Este comando crea los archivos de build en el directorio 'build'

    - name: Verify build directory exists
      run: ls -la build  # Verifica que el directorio build se haya creado correctamente

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: build  # Directorio donde se guardan los archivos compilados

  deploy:
    needs: build  # Este job se ejecuta solo si el build fue exitoso
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-files

    - name: Verify build directory exists
      run: ls -la build  # Verifica que el directorio se haya descargado correctamente

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync files to S3
      run: aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }} --delete
      # El flag --delete asegura que los archivos obsoletos se eliminen del bucket
