name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push a la rama main (puedes cambiarla)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Versión de Node.js que deseas usar (puedes cambiarla)

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build  # Este comando genera los archivos para producción (build)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: build  # Directorio donde se generan los archivos (usualmente 'build' en React)

  deploy:
    needs: build  # El job 'deploy' depende de que 'build' haya sido exitoso
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-files

    - name: Upload to S3
      uses: aws-actions/s3-sync-action@v2
      with:
        bucket: ${{ secrets.AWS_S3_BUCKET }}  # Nombre del bucket S3 (configurado en secrets)
        region: ${{ secrets.AWS_REGION }}     # Región de tu bucket S3
        source-dir: build                     # Directorio con los archivos que se subirán
        delete: true                          # Elimina archivos en el bucket que no están en el build actual

    - name: Invalidate CloudFront cache (opcional)
      uses: chetan/invalidate-cloudfront-action@v1
      with:
        distribution-id: ${{ secrets.AWS_CLOUDFRONT_ID }}  # Distribución de CloudFront (opcional)
        paths: '/*'
